#!/bin/bash

# Run Atlantis

/home/sjor/johannes/Vinna/Atlantis/atlantis/atlantismain/atlantisMerged -i InitialCond89.nc 0 -o Out.nc -r Run.prm -f Force.prm -p Physics.prm -b B371.prm -s GroupsIceland.csv -q FisheriesIceland.csv -h F140.prm -d test_run

    
	
 
